### PR TITLE
📄 Add license file

### LINKED ISSUE #22: Adopt a license
Right now there is no license here so it'd be best to adopt one.

Thoughts? @Carreau

### PR DESCRIPTION
**Pull request by trallard**
- :page_facing_up: Add license file
- :memo: Add license wording to the readme

Closes #22

### CODE REVIEW

**Comment by bskinn** [comment]
We'll want to change the license wording in the footer of the site, too. It's not correct for the graphical assets.

**Comment by trallard** [comment]
Fixed wording in the site too now

**Review by bskinn — APPROVED** [review]
Maybe a slight tweak, "Remaining website content licensed under ...", in the page footer?

Otherwise, LGTM. Thanks!

**Comment by trallard** [comment]
I do not think the additional "remaining" is needed. 
Will go ahead an merge - next time @bskinn  if you approve a PR can you merge too? thanks

**Pull request merged**
